[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/ressources"
  to = "/ressources.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog/index.html"
  status = 200

[[headers]]
  for = "/assets/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "inline"
